# Actuators
actuator_names:
  - left_gripper_prismatic_joint_motor
  - left_gripper_vacuum_pad_tendon_winder
  - left_gripper_finger_yaw_joint_motor
  - left_gripper_finger_roll_joint_a_virtual_motor
  - left_gripper_finger_roll_joint_b_virtual_motor
joint_names:
  - left_gripper_prismatic_joint
  - left_gripper_vacuum_pad_joint
  - left_gripper_finger_yaw_joint
  - left_gripper_finger_roll_joint_a
  - left_gripper_finger_roll_joint_b
mechanical_reduction:
  - 35.71428571  # 1 / (0.8 * 35 * 0.001)
  - 1.432291667
  - 1.5625  # ~ 36 / 24
  - 1.0
  - 1.0
virtual_actuators:
  - virtual:
      - left_gripper_finger_roll_joint_a_virtual_motor
      - left_gripper_finger_roll_joint_b_virtual_motor
    real:
      - left_gripper_finger_tendon_winder
    # Add following sections when we have to implement other relationship
    # actuator_command_conversion:
    #   method: Addition
    # actuator_state_conversion:
    #   method: Division
    #   apply_joint_limit: true
controllers:
  left_gripper_prismatic_joint_motor: prismatic_joint_controller
  left_gripper_vacuum_pad_tendon_winder: vacuum_pad_tendon_controller
  left_gripper_finger_yaw_joint_motor: finger_yaw_joint_controller
  left_gripper_finger_tendon_winder: finger_tendon_controller

# Flex sensors
flex_names:
  - right
  - left
#flex_thresholds:
#  - 680
#  - 690
flex_thresholds:
  - 5000
  - 5000
wind_offset_flex:
  - 0.5
  - 0.5

# Proximity sensors
proximity_sensor_num: 1

control_rate: 100
