# Actuators
actuator_names:
  - left_gripper_prismatic_joint_motor
  - left_gripper_vacuum_pad_tendon_winder
  - left_gripper_finger_yaw_joint_motor
  - left_gripper_finger_tendon_winder
controller_names:
  - prismatic_joint_controller
  - vacuum_pad_tendon_controller
  - finger_yaw_joint_controller
  - finger_tendon_controller

# Flex sensors
flex_names:
  - right
  - left
#flex_thresholds:
#  - 680
#  - 690
flex_thresholds:
  - 5000
  - 5000
wind_offset_flex:
  - 0.5
  - 0.5

# Proximity sensors
proximity_sensor_num: 2

control_rate: 100
