# Actuators
actuator_names:
  - left_gripper_prismatic_joint_motor
  - left_gripper_vacuum_pad_tendon_winder
  - left_gripper_finger_yaw_joint_motor
  - left_gripper_finger_tendon_winder
joint_names:
  - left_gripper_prismatic_joint
  - left_gripper_vacuum_pad_joint
  - left_gripper_finger_yaw_joint
  - left_gripper_finger_roll_joint
controller_names:
  - prismatic_joint_controller
  - vacuum_pad_tendon_controller
  - finger_yaw_joint_controller
  - finger_tendon_controller
mechanical_reduction:
  - 35.71428571  # 1 / (0.8 * 35 * 0.001)
  - 1.432291667
  - 1.5625  # ~ 36 / 24
  - 1.5

# Flex sensors
flex_names:
  - right
  - left
#flex_thresholds:
#  - 680
#  - 690
flex_thresholds:
  - 5000
  - 5000
wind_offset_flex:
  - 0.5
  - 0.5

control_rate: 100
